# Generated by Django 2.1 on 2021-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='careers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=50)),
                ('Job_description', models.CharField(max_length=500)),
                ('Required_education', models.CharField(choices=[('High School.', 'High School'), ('Diploma.', 'Diploma'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('PhD', 'PhD')], max_length=10)),
                ('Education_fields', models.CharField(max_length=100)),
                ('Desired_qualifications', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Careers',
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Company')),
                ('date_established', models.DateField(verbose_name='Date of Establishment')),
                ('Telephone1', models.CharField(max_length=20, verbose_name='Primary Contact Number')),
                ('Telephone2', models.CharField(blank=True, max_length=20, verbose_name='Secondary Contact Number')),
                ('Email1', models.CharField(blank=True, max_length=50, verbose_name='Primary Email')),
                ('Email2', models.CharField(max_length=50, verbose_name='Secondary Email')),
                ('Address', models.CharField(max_length=100, verbose_name='Physical Address')),
                ('facebook_handle', models.CharField(max_length=50)),
                ('instagram_handle', models.CharField(max_length=50)),
                ('twitter_handle', models.CharField(max_length=50)),
                ('linkedin_handle', models.CharField(max_length=50)),
                ('youtube_channel', models.CharField(max_length=50)),
                ('Logo', models.ImageField(upload_to='company/')),
                ('Favicon', models.ImageField(upload_to='company/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name of Founder')),
                ('Founder_photo', models.ImageField(upload_to='founder/')),
                ('Founder_description', models.CharField(max_length=500)),
                ('facebook_handle', models.CharField(max_length=50)),
                ('instagram_handle', models.CharField(max_length=50)),
                ('twitter_handle', models.CharField(max_length=50)),
                ('linkedin_handle', models.CharField(max_length=50)),
                ('youtube_channel', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Founder',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Partner')),
                ('relationship', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='Partners/')),
            ],
            options={
                'verbose_name_plural': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('service_description', models.CharField(max_length=200)),
                ('service_icon', models.ImageField(upload_to='Services/')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Team_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name of Member')),
                ('Member_photo', models.ImageField(upload_to='Team_members/')),
                ('Member_description', models.CharField(max_length=500)),
                ('facebook_handle', models.CharField(max_length=50)),
                ('instagram_handle', models.CharField(max_length=50)),
                ('twitter_handle', models.CharField(max_length=50)),
                ('linkedin_handle', models.CharField(max_length=50)),
                ('youtube_channel', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
