# Generated by Django 2.1 on 2021-03-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quoterequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=50)),
                ('sender_name', models.CharField(max_length=50)),
                ('service_request', models.CharField(max_length=200)),
                ('urgency', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('project_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='founder',
        ),
    ]
