# Generated by Django 2.1 on 2021-03-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210302_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Name of Founder')),
                ('Founder_photo', models.ImageField(upload_to='founder/')),
                ('Founder_description', models.CharField(max_length=500)),
                ('contact_number', models.CharField(max_length=15)),
                ('facebook_handle', models.CharField(max_length=50)),
                ('instagram_handle', models.CharField(max_length=50)),
                ('twitter_handle', models.CharField(max_length=50)),
                ('linkedin_handle', models.CharField(max_length=50)),
                ('youtube_channel', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Founder',
            },
        ),
    ]
