# Generated by Django 2.1 on 2021-03-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_founder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quoterequest',
        ),
    ]
