# Generated by Django 2.1 on 2021-03-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('feature_icon', models.ImageField(upload_to='Features/')),
                ('feature_description', models.CharField(max_length=200)),
            ],
        ),
    ]
