# Generated by Django 2.1 on 2021-03-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimomials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('review_comment', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name_plural': 'Features'},
        ),
    ]
