# Generated by Django 2.1 on 2021-03-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210303_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='onlineshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Online Shops',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='onlineshop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.onlineshop'),
        ),
    ]
